/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigTemplate
 */
export interface ConfigTemplate {
    /**
     * 配置模板ID
     * @type {string}
     * @memberof ConfigTemplate
     */
    id: string;
    /**
     * 所属的配置组ID
     * @type {string}
     * @memberof ConfigTemplate
     */
    groupId?: string;
    /**
     * 配置项
     * @type {string}
     * @memberof ConfigTemplate
     */
    key: string;
    /**
     * 配置内容
     * @type {object}
     * @memberof ConfigTemplate
     */
    value: object;
    /**
     * 创建时间
     * @type {Date}
     * @memberof ConfigTemplate
     */
    createdAt: Date;
    /**
     * 最后更新时间
     * @type {Date}
     * @memberof ConfigTemplate
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ConfigTemplate interface.
 */
export function instanceOfConfigTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ConfigTemplateFromJSON(json: any): ConfigTemplate {
    return ConfigTemplateFromJSONTyped(json, false);
}

export function ConfigTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'groupId': !exists(json, 'group_id') ? undefined : json['group_id'],
        'key': json['key'],
        'value': json['value'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ConfigTemplateToJSON(value?: ConfigTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'group_id': value.groupId,
        'key': value.key,
        'value': value.value,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

