/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigGroup
 */
export interface ConfigGroup {
    /**
     * 配置组ID
     * @type {string}
     * @memberof ConfigGroup
     */
    id: string;
    /**
     * 配置组名称
     * @type {string}
     * @memberof ConfigGroup
     */
    name: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof ConfigGroup
     */
    createdAt: Date;
    /**
     * 最后更新时间
     * @type {Date}
     * @memberof ConfigGroup
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ConfigGroup interface.
 */
export function instanceOfConfigGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ConfigGroupFromJSON(json: any): ConfigGroup {
    return ConfigGroupFromJSONTyped(json, false);
}

export function ConfigGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ConfigGroupToJSON(value?: ConfigGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

