/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConfig
 */
export interface CreateConfig {
    /**
     * 所属的资源ID
     * @type {string}
     * @memberof CreateConfig
     */
    resourceId: string;
    /**
     * 所属的配置组ID
     * @type {string}
     * @memberof CreateConfig
     */
    groupId?: string;
    /**
     * 配置模板ID
     * @type {string}
     * @memberof CreateConfig
     */
    templateId?: string;
    /**
     * 配置项
     * @type {string}
     * @memberof CreateConfig
     */
    key: string;
    /**
     * 配置内容
     * @type {object}
     * @memberof CreateConfig
     */
    value: object;
}

/**
 * Check if a given object implements the CreateConfig interface.
 */
export function instanceOfCreateConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CreateConfigFromJSON(json: any): CreateConfig {
    return CreateConfigFromJSONTyped(json, false);
}

export function CreateConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': json['resource_id'],
        'groupId': !exists(json, 'group_id') ? undefined : json['group_id'],
        'templateId': !exists(json, 'template_id') ? undefined : json['template_id'],
        'key': json['key'],
        'value': json['value'],
    };
}

export function CreateConfigToJSON(value?: CreateConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_id': value.resourceId,
        'group_id': value.groupId,
        'template_id': value.templateId,
        'key': value.key,
        'value': value.value,
    };
}

