/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConfigGroup
 */
export interface CreateConfigGroup {
    /**
     * 配置组名称
     * @type {string}
     * @memberof CreateConfigGroup
     */
    name: string;
}

/**
 * Check if a given object implements the CreateConfigGroup interface.
 */
export function instanceOfCreateConfigGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateConfigGroupFromJSON(json: any): CreateConfigGroup {
    return CreateConfigGroupFromJSONTyped(json, false);
}

export function CreateConfigGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConfigGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateConfigGroupToJSON(value?: CreateConfigGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

