/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConfigTemplate
 */
export interface CreateConfigTemplate {
    /**
     * 所属的配置组ID
     * @type {string}
     * @memberof CreateConfigTemplate
     */
    groupId?: string;
    /**
     * 配置项
     * @type {string}
     * @memberof CreateConfigTemplate
     */
    key: string;
    /**
     * 配置内容
     * @type {object}
     * @memberof CreateConfigTemplate
     */
    value: object;
}

/**
 * Check if a given object implements the CreateConfigTemplate interface.
 */
export function instanceOfCreateConfigTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function CreateConfigTemplateFromJSON(json: any): CreateConfigTemplate {
    return CreateConfigTemplateFromJSONTyped(json, false);
}

export function CreateConfigTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConfigTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': !exists(json, 'group_id') ? undefined : json['group_id'],
        'key': json['key'],
        'value': json['value'],
    };
}

export function CreateConfigTemplateToJSON(value?: CreateConfigTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_id': value.groupId,
        'key': value.key,
        'value': value.value,
    };
}

