/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 短信服务商
 * @export
 */
export const Provider = {
    Qcloud: 'qcloud',
    Aliyun: 'aliyun'
} as const;
export type Provider = typeof Provider[keyof typeof Provider];


export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    return json as Provider;
}

export function ProviderToJSON(value?: Provider | null): any {
    return value as any;
}

