/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SMSProvider } from './SMSProvider';
import {
    SMSProviderFromJSON,
    SMSProviderFromJSONTyped,
    SMSProviderToJSON,
} from './SMSProvider';

/**
 * 
 * @export
 * @interface SendSMSResult
 */
export interface SendSMSResult {
    /**
     * 是否发送成功
     * @type {boolean}
     * @memberof SendSMSResult
     */
    success: boolean;
    /**
     * 
     * @type {SMSProvider}
     * @memberof SendSMSResult
     */
    provider: SMSProvider;
    /**
     * 服务商返回的请求ID
     * @type {string}
     * @memberof SendSMSResult
     */
    provierRequestId?: string;
}

/**
 * Check if a given object implements the SendSMSResult interface.
 */
export function instanceOfSendSMSResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "provider" in value;

    return isInstance;
}

export function SendSMSResultFromJSON(json: any): SendSMSResult {
    return SendSMSResultFromJSONTyped(json, false);
}

export function SendSMSResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendSMSResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'provider': SMSProviderFromJSON(json['provider']),
        'provierRequestId': !exists(json, 'provier_request_id') ? undefined : json['provier_request_id'],
    };
}

export function SendSMSResultToJSON(value?: SendSMSResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'provider': SMSProviderToJSON(value.provider),
        'provier_request_id': value.provierRequestId,
    };
}

