/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConfigTemplate
 */
export interface UpdateConfigTemplate {
    /**
     * 所属的配置组ID
     * @type {string}
     * @memberof UpdateConfigTemplate
     */
    groupId?: string;
    /**
     * 配置项
     * @type {string}
     * @memberof UpdateConfigTemplate
     */
    key?: string;
    /**
     * 配置内容
     * @type {object}
     * @memberof UpdateConfigTemplate
     */
    value?: object;
}

/**
 * Check if a given object implements the UpdateConfigTemplate interface.
 */
export function instanceOfUpdateConfigTemplate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateConfigTemplateFromJSON(json: any): UpdateConfigTemplate {
    return UpdateConfigTemplateFromJSONTyped(json, false);
}

export function UpdateConfigTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConfigTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': !exists(json, 'group_id') ? undefined : json['group_id'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function UpdateConfigTemplateToJSON(value?: UpdateConfigTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_id': value.groupId,
        'key': value.key,
        'value': value.value,
    };
}

