/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateConfigGroup
 */
export interface UpdateConfigGroup {
    /**
     * 配置组名称
     * @type {string}
     * @memberof UpdateConfigGroup
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateConfigGroup interface.
 */
export function instanceOfUpdateConfigGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateConfigGroupFromJSON(json: any): UpdateConfigGroup {
    return UpdateConfigGroupFromJSONTyped(json, false);
}

export function UpdateConfigGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConfigGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateConfigGroupToJSON(value?: UpdateConfigGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

