/* tslint:disable */
/* eslint-disable */
/**
 * xapi services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Provider } from './Provider';
import {
    ProviderFromJSON,
    ProviderFromJSONTyped,
    ProviderToJSON,
} from './Provider';

/**
 * 
 * @export
 * @interface VideoSnapshot
 */
export interface VideoSnapshot {
    /**
     * 
     * @type {Provider}
     * @memberof VideoSnapshot
     */
    provider: Provider;
    /**
     * 截图的链接地址
     * @type {string}
     * @memberof VideoSnapshot
     */
    url: string;
}

/**
 * Check if a given object implements the VideoSnapshot interface.
 */
export function instanceOfVideoSnapshot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "provider" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function VideoSnapshotFromJSON(json: any): VideoSnapshot {
    return VideoSnapshotFromJSONTyped(json, false);
}

export function VideoSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': ProviderFromJSON(json['provider']),
        'url': json['url'],
    };
}

export function VideoSnapshotToJSON(value?: VideoSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': ProviderToJSON(value.provider),
        'url': value.url,
    };
}

